# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type_id', models.CharField(choices=[(b'6-flat', b'6-flat'), (b'96-flat-tc', b'96-flat-tc'), (b'384-flat-white-white-tc', b'384-flat-white-white-tc'), (b'384-pcr', b'384-pcr'), (b'24-deep', b'24-deep'), (b'96-flat', b'96-flat'), (b'1-flat', b'1-flat'), (b'96-deep', b'96-deep'), (b'96-v-kf', b'96-v-kf'), (b'screw-cap-1.8', b'screw-cap-1.8'), (b'96-flat-clear-clear-tc', b'96-flat-clear-clear-tc'), (b'6-flat-tc', b'6-flat-tc'), (b'96-pcr', b'96-pcr'), (b'384-flat', b'384-flat'), (b'96-flat-uv', b'96-flat-uv'), (b'384-flat-clear-clear', b'384-flat-clear-clear'), (b'384-echo', b'384-echo'), (b'96-deep-kf', b'96-deep-kf'), (b'micro-1.5', b'micro-1.5'), (b'micro-2.0', b'micro-2.0'), (b'384-flat-white-white-lv', b'384-flat-white-white-lv')], max_length=200)),
            ],
        ),
    ]
