# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 16:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='barcode',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='cover',
            field=models.CharField(choices=[(b'low_evaporation', b'low_evaporation'), (b'universal', b'universal'), (b'standard', b'standard')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='label',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sample',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[(b'384-pcr', b'384-pcr'), (b'384-flat-white-white-nbs', b'384-flat-white-white-nbs'), (b'96-deep', b'96-deep'), (b'96-flat-clear-clear-tc', b'96-flat-clear-clear-tc'), (b'6-flat-tc', b'6-flat-tc'), (b'96-flat', b'96-flat'), (b'96-pcr', b'96-pcr'), (b'24-deep', b'24-deep'), (b'384-flat', b'384-flat'), (b'96-flat-uv', b'96-flat-uv'), (b'384-echo', b'384-echo'), (b'384-flat-white-white-tc', b'384-flat-white-white-tc'), (b'screw-cap-1.8', b'screw-cap-1.8'), (b'384-v-clear-clear', b'384-v-clear-clear'), (b'micro-2.0', b'micro-2.0'), (b'6-flat', b'6-flat'), (b'96-flat-tc', b'96-flat-tc'), (b'micro-1.5', b'micro-1.5'), (b'1-flat', b'1-flat'), (b'96-v-kf', b'96-v-kf'), (b'384-round-clear-clear', b'384-round-clear-clear'), (b'384-flat-clear-clear', b'384-flat-clear-clear'), (b'96-deep-kf', b'96-deep-kf'), (b'384-flat-white-white-lv', b'384-flat-white-white-lv')], default='available', max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_condition',
            field=models.CharField(choices=[(b'cold_4', b'cold_4'), (b'cold_20', b'cold_20'), (b'cold_80', b'cold_80'), (b'warm_37', b'warm_37'), (b'ambient', b'ambient')], default=b'ambient', max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='container_type_id',
            field=models.CharField(choices=[(b'384-pcr', b'384-pcr'), (b'384-flat-white-white-nbs', b'384-flat-white-white-nbs'), (b'96-deep', b'96-deep'), (b'96-flat-clear-clear-tc', b'96-flat-clear-clear-tc'), (b'6-flat-tc', b'6-flat-tc'), (b'96-flat', b'96-flat'), (b'96-pcr', b'96-pcr'), (b'24-deep', b'24-deep'), (b'384-flat', b'384-flat'), (b'96-flat-uv', b'96-flat-uv'), (b'384-echo', b'384-echo'), (b'384-flat-white-white-tc', b'384-flat-white-white-tc'), (b'screw-cap-1.8', b'screw-cap-1.8'), (b'384-v-clear-clear', b'384-v-clear-clear'), (b'micro-2.0', b'micro-2.0'), (b'6-flat', b'6-flat'), (b'96-flat-tc', b'96-flat-tc'), (b'micro-1.5', b'micro-1.5'), (b'1-flat', b'1-flat'), (b'96-v-kf', b'96-v-kf'), (b'384-round-clear-clear', b'384-round-clear-clear'), (b'384-flat-clear-clear', b'384-flat-clear-clear'), (b'96-deep-kf', b'96-deep-kf'), (b'384-flat-white-white-lv', b'384-flat-white-white-lv')], max_length=200),
        ),
    ]
