# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0002_initial_organization_and_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterIndexTogether(
            name='run',
            index_together=set([('project', 'test_mode', 'status')]),
        ),
    ]
