# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0002_initial_organization_and_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations', related_query_name='orgnization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('aborted', 'aborted'), ('canceled', 'canceled')], default='accepted', max_length=200),
        ),
    ]
