# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Organization = apps.get_model("autolims", "Organization")
    db_alias = schema_editor.connection.alias
    Organization.objects.using(db_alias).bulk_create([
        Organization(name="Default Organization", subdomain='default',
                     id=1)
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Organization = apps.get_model("autolims", "Organization")
    db_alias = schema_editor.connection.alias
    Organization.objects.using(db_alias).filter(id=1).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0002_auto_20170115_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('well_idx', models.IntegerField(default=0)),
                ('volume_ul', models.CharField(default='0', max_length=200)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquots', related_query_name='aliquot', to='autolims.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('subdomain', models.CharField(max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
