# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0003_auto_20170120_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('aborted', 'aborted'), ('canceled', 'canceled')], default='available', max_length=200),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('aborted', 'aborted'), ('canceled', 'canceled')], default='available', max_length=200),
        ),
        migrations.AlterField(
            model_name='run',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
