# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autolims', '0003_aliquot_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('bsl', models.IntegerField(default=1)),
                ('archived_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('accepted', 'accepted'), ('in-progress', 'in-progress'), ('aborted', 'aborted'), ('canceled', 'canceled')], default='available', max_length=200)),
                ('test_mode', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(null=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('aborted_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', related_query_name='run', to='autolims.Project')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='containers', related_query_name='container', to='autolims.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('destroyed', 'destroyed'), ('returned', 'returned'), ('inbound', 'inbound'), ('outbound', 'outbound')], default='available', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='autolims.Organization'),
        ),
        migrations.AddField(
            model_name='sample',
            name='generated_by_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_containers', related_query_name='generated_container', to='autolims.Run'),
        ),
    ]
