# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 17:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0006_auto_20170116_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('effect_type', models.CharField(choices=[('liquid_transfer_in', 'liquid_transfer_in'), ('liquid_transfer_out', 'liquid_transfer_out'), ('instruction', 'instruction')], default='liquid_transfer_in', max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_aliquot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquot_effects', related_query_name='aliquot_effect', to='autolims.Aliquot')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('data_type', models.CharField(choices=[('image_plate', 'image_plate'), ('platereader', 'platereader'), ('measure', 'measure')], default='available', max_length=200)),
                ('sequence_no', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dummy value')),
                ('file', models.FileField(blank=True, null=True, upload_to='dummy value')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('sequence_no', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='refs',
            field=models.ManyToManyField(related_name='related_runs', related_query_name='related_run', to='autolims.Sample'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', related_query_name='instruction', to='autolims.Run'),
        ),
        migrations.AddField(
            model_name='data',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', related_query_name='data', to='autolims.Instruction'),
        ),
        migrations.AddField(
            model_name='data',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', related_query_name='data', to='autolims.Run'),
        ),
        migrations.AddField(
            model_name='aliquoteffect',
            name='generating_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquot_effects', related_query_name='aliquot_effect', to='autolims.Instruction'),
        ),
        migrations.AlterUniqueTogether(
            name='instruction',
            unique_together=set([('run', 'sequence_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('run', 'sequence_no')]),
        ),
    ]
