# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0007_auto_20170116_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='autolims.Data/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='autolims.Data/bytes/filename/mimetype'),
        ),
    ]
