# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0008_auto_20170116_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'data'},
        ),
    ]
