# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0009_auto_20170116_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliquoteffect',
            name='effect_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='operation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='refs',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_runs', related_query_name='related_run', to='autolims.Sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
