# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0010_auto_20170116_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', related_query_name='data', to='autolims.Instruction'),
        ),
    ]
