# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0011_auto_20170116_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='autolims.DataFile/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='autolims.DataImage/bytes/filename/mimetype'),
        ),
    ]
