# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

from transcriptic_resources import TRANSCRIPTIC_RESOURCES

OUR_RESOURCES = []

ALL_RESOURCES = TRANSCRIPTIC_RESOURCES + OUR_RESOURCES

def forwards_create_org_func(apps, schema_editor):
    Organization = apps.get_model("autolims", "Organization")
    db_alias = schema_editor.connection.alias
    Organization.objects.using(db_alias).bulk_create([
        Organization(name="Default Organization", subdomain='default')
    ])

def reverse_create_org_func(apps, schema_editor):
    Organization = apps.get_model("autolims", "Organization")
    db_alias = schema_editor.connection.alias
    Organization.objects.using(db_alias).filter(id=1).delete()
    
    
def forwards_create_resources_func(apps, schema_editor):
    Resource = apps.get_model("autolims", "Resource")
    db_alias = schema_editor.connection.alias
    Resource.objects.using(db_alias).bulk_create([
        Resource(name=resource_dict['name'], 
                 storage_condition=resource_dict['storage_condition'],
                 description=resource_dict['description'], 
                 sensitivities=resource_dict['sensitivities'], 
                 properties=resource_dict['properties'], 
                 kind=resource_dict['kind'], 
                 transcriptic_id=resource_dict['transcriptic_id'], 
                 )
        for resource_dict in ALL_RESOURCES
    ])

def reverse_create_resources_func(apps, schema_editor):
    Resource = apps.get_model("autolims", "Resource")
    db_alias = schema_editor.connection.alias
    Resource.objects.using(db_alias).all().delete()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('autolims', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_create_org_func, reverse_create_org_func),
        migrations.RunPython(forwards_create_resources_func, reverse_create_resources_func),
    ]
