TRANSCRIPTIC_RESOURCES = [   {   'description': None,
        'kind': u'Reagent',
        'name': u'Methanol',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'ambient',
        'transcriptic_id': 'rs196bbr78dppk'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Reaction Buffer A',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pc9rd5sg5d'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'LB Miller Amp 100',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs18s8x4qbsvjz'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'TE',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs17pwyc754v9t'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Ampicillin 100mg/ml',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17msfk8ujkca'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Q5 High GC Enhancer',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pcce8rva4a'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'ATP',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pccshb6cb4'},
    {   'description': None,
        'kind': u'NucleicAcid',
        'name': u'pHSG298 100pg/ul',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs18rx6a44qss7'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Penicillin-Streptomycin (5,000 U/mL)',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs196bavhs85mh'},
    {   'description': None,
        'kind': u'NucleicAcid',
        'name': u'M13 Reverse (-48) 100uM',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17tcph6e2qzh'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'CutSmart Buffer 10x',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17ta93g3y85t'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Glycerol 40%',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'ambient',
        'transcriptic_id': 'rs17rrhqpsxyh2'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'FBS',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs196baqxcecxs'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'DMEM + 10%(FBS, L-Glut, PS)',
        'properties': {   },
        'sensitivities': [u'Air'],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs197gzgq2fufr'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Zymo DH5\u03b1',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_80',
        'transcriptic_id': 'rs16pbj944fnny'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'24% PEG 6000 Solution',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'ambient',
        'transcriptic_id': 'rs16pc9rd68sdt'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'T4 DNA Ligase (NEB)',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pc8krr6ag7'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Water',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'ambient',
        'transcriptic_id': 'rs17gmh5wafm5p'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'T4 Polynucleotide Kinase',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pc9rd5hsf6'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'DMSO (Ultra-pure)',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs186hr8m38ntw'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'HindIII-HF (NEB)',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs18nw6kpnp44v'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'LB Miller Kan 50',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs18s8x88zz9ee'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Chloramphenicol',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17p6t8ty2ny4'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'SensiFAST SYBR No-ROX',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17knkh7526ha'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'SalI-HF (NEB)',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs18y5qx47z4v2'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'LB Miller',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs17bafcbmyrmh'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Gibson Mix (2x)',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pfatkggmk5'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'MEM',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs196bbjnnayuk'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'M9 minimal media',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs18tmbm3am3ab'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'SOC Medium',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs17tpdy56hfar'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Trypsin-EDTA (0.25%), phenol red',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs196bb2deuhsy'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Q5 High-Fidelity DNA Polymerase',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pcce8rdytv'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Kanamycin 50mg/ml',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17msfpgpbqyv'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'FastAP Thermosensitive Alkaline Phosphatase',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pc9925vae3'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Antarctic Phosphatase (NEB)',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17sh65xxym4k'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Antarctic Phosphatase Reaction Buffer 10X (NEB)',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17sh6bqyawz3'},
    {   'description': None,
        'kind': u'NucleicAcid',
        'name': u'pHSG298 0.5ug/ul',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs18rx5pyh6fku'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Spectinomycin 100mg/ml',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17pm6deqjep7'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'NEBuffer 2.1 10X',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17sh6krrzjqu'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Q5 Reaction Buffer',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs16pcce8rmke3'},
    {   'description': None,
        'kind': u'NucleicAcid',
        'name': u'pUC19 100pg/ul',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs18rx59spw2t8'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Lipofectamine 2000',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs196bb7qetqmr'},
    {   'description': None,
        'kind': u'NucleicAcid',
        'name': u'pUC19 1mg/ml',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17tcqmncjfsh'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'dNTP Mixture (10mM each)',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs186wj7fvknsr'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Phosphate Buffer Saline, pH 7.2',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'ambient',
        'transcriptic_id': 'rs194na2u3hfam'},
    {   'description': None,
        'kind': u'NucleicAcid',
        'name': u'M13 Forward (-41) 100uM',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17tcpqwqcaxe'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'Opti-MEM I Reduced Serum Medium',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs196bbe9yqma8'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'T4 DNA Ligase Reaction Buffer 10x (NEB)',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs17sh5rzz79ct'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'TSS (Transformation & Storage solution) pH 6.5',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs19gme9ycpux6'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'NEBuilder HiFi DNA Assembly Master Mix',
        'properties': {   },
        'sensitivities': [u'Temperature'],
        'storage_condition': u'cold_20',
        'transcriptic_id': 'rs18pc86ykcep6'},
    {   'description': None,
        'kind': u'Reagent',
        'name': u'IPTG 100mM',
        'properties': {   },
        'sensitivities': [],
        'storage_condition': u'cold_4',
        'transcriptic_id': 'rs18vwgfgxq597'}]
